from typing import Any, Protocol

from .models import ParsedChunk, SearchHit


class MetadataRepository(Protocol):
    def initialize(self) -> None: ...
    def knowledge_base_exists(self, knowledge_base_id: str) -> bool: ...
    def create_knowledge_base(self, knowledge_base_id: str, name: str, description: str, embedding_model: str) -> dict[str, Any]: ...
    def list_knowledge_bases(self) -> list[dict[str, Any]]: ...
    def get_knowledge_base(self, knowledge_base_id: str) -> dict[str, Any] | None: ...
    def create_document(self, item: dict[str, Any]) -> None: ...
    def update_document(self, document_id: str, **fields: Any) -> None: ...
    def get_document(self, document_id: str) -> dict[str, Any] | None: ...
    def list_documents(self, knowledge_base_id: str) -> list[dict[str, Any]]: ...
    def replace_chunks(self, document_id: str, knowledge_base_id: str, chunks: list[ParsedChunk]) -> None: ...
    def add_message(self, knowledge_base_id: str, question: str, answer: str, citations: list[dict[str, Any]]) -> None: ...


class ObjectStore(Protocol):
    def ensure_bucket(self) -> None: ...
    def put_bytes(self, object_key: str, content: bytes, content_type: str) -> None: ...


class VectorStore(Protocol):
    def ensure_collection(self, vector_size: int) -> None: ...
    def upsert(self, points: list[dict[str, Any]], vectors: list[list[float]]) -> None: ...
    def search(self, knowledge_base_id: str, vector: list[float], limit: int) -> list[SearchHit]: ...


class DocumentParser(Protocol):
    def supports(self, file_name: str) -> bool: ...
    def parse(self, file_name: str, content: bytes) -> list[ParsedChunk]: ...


class ModelGateway(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def answer(self, question: str, context: str) -> str: ...
