from typing import Any, Protocol

from .models import ParsedChunk, SearchHit


class MetadataRepository(Protocol):
    def initialize(self) -> None: ...
    def knowledge_base_exists(self, knowledge_base_id: str, owner_id: str | None = None) -> bool: ...
    def create_knowledge_base(self, knowledge_base_id: str, name: str, description: str, embedding_model: str, owner_id: str = "personal") -> dict[str, Any]: ...
    def list_knowledge_bases(self, owner_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_knowledge_base(self, knowledge_base_id: str, owner_id: str | None = None) -> dict[str, Any] | None: ...
    def create_document(self, item: dict[str, Any]) -> None: ...
    def update_document(self, document_id: str, **fields: Any) -> None: ...
    def get_document(self, document_id: str) -> dict[str, Any] | None: ...
    def document_exists_by_file(self, knowledge_base_id: str, file_name: str, folder_path: str) -> bool: ...
    def list_documents(self, knowledge_base_id: str) -> list[dict[str, Any]]: ...
    def delete_document(self, document_id: str) -> None: ...
    def delete_knowledge_base(self, knowledge_base_id: str) -> None: ...
    def replace_chunks(self, document_id: str, knowledge_base_id: str, chunks: list[ParsedChunk], folder_path: str = "") -> None: ...
    def create_conversation(self, conversation_id: str, knowledge_base_id: str, title: str) -> dict[str, Any]: ...
    def get_conversation(self, conversation_id: str, owner_id: str | None = None) -> dict[str, Any] | None: ...
    def list_conversations(self, knowledge_base_id: str, owner_id: str | None = None) -> list[dict[str, Any]]: ...
    def update_conversation_title(self, conversation_id: str, title: str) -> dict[str, Any] | None: ...
    def delete_conversation(self, conversation_id: str) -> None: ...
    def add_message(self, conversation_id: str, knowledge_base_id: str, question: str, answer: str, citations: list[dict[str, Any]]) -> None: ...
    def list_messages(self, conversation_id: str) -> list[dict[str, Any]]: ...


class ObjectStore(Protocol):
    def ensure_bucket(self) -> None: ...
    def put_bytes(self, object_key: str, content: bytes, content_type: str) -> None: ...
    def delete_object(self, object_key: str) -> None: ...


class VectorStore(Protocol):
    def ensure_collection(self, vector_size: int) -> None: ...
    def upsert(self, points: list[dict[str, Any]], vectors: list[list[float]]) -> None: ...
    def search(self, knowledge_base_id: str, vector: list[float], limit: int) -> list[SearchHit]: ...
    def delete_document(self, document_id: str) -> None: ...
    def delete_knowledge_base(self, knowledge_base_id: str) -> None: ...


class DocumentParser(Protocol):
    def supports(self, file_name: str) -> bool: ...
    def parse(self, file_name: str, content: bytes) -> list[ParsedChunk]: ...


class ModelGateway(Protocol):
    chat_model: str
    embedding_model: str

    def list_chat_models(self) -> list[dict[str, Any]]: ...
    def complete(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
        temperature: float = 0.1,
        max_tokens: int | None = None,
        reasoning: bool | None = None,
        response_schema: dict[str, Any] | None = None,
    ) -> str: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
